services:
  apivallabus:
    build: .
    container_name: apivallabus
    image: vallabus/apivallabus:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
