services:
  apiauvasa-ecsa:
    build: .
    container_name: apiauvasa-ecsa
    image: apiauvasa-ecsa:latest
    ports:
      - 3030:3000
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
