# Simple workflow for deploying static content to GitHub Pages
name: Update GTFS static files

on:
  workflow_dispatch:
  schedule:
  - cron: '35 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run getGtfs
        git config user.name github-actions-bot
        git config user.email github-actions-bot@github.com
        git add gtfs-files
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update GTFS static files"
        git push origin main
